### ISSUE TITLE
Is `RVIZ` visualization available?

### ISSUE THREAD

**Issue by kevintsq** [snktshrma/obstacle_cluster_detection#3]

**Comment by snktshrma** [comment]
Yup!
Just add Laser Scan in rviz and use the appropriate topic.
![Screenshot from 2022-08-09 18-24-24](https://user-images.githubusercontent.com/74557164/183652017-53b9c03d-c4bf-451e-8170-d303178b9045.png)

**Comment by kevintsq** [comment]
Thanks! I'll try it out when my device is available.

**Comment by snktshrma** [comment]
So I'll probably close this issue for now. If the issue persists, will reopen it
