### ISSUE TITLE
dynamic memory allocation 

### ISSUE THREAD

**Issue by rohithsaro** [snktshrma/obstacle_cluster_detection#4]
```
process[cluster_counter-1]: started with pid [13925]
[ INFO] [1712068500.978214743]: Length of Array = 720
[ INFO] [1712068500.981197369]: No. of Clusters : 31
[ INFO] [1712068500.981261335]: No. of Points in 
free(): double free detected in tcache 2
[cluster_counter-1] process has died [pid 13925, exit code -6, cmd /home/name/catkin_ws/devel/lib/cluster_counter/cluster_counter __name:=cluster_counter 
```

there is a issue where the program is trying to free memory that has already been freed.

thank you for the work.

**Comment by rohithsaro** [comment]
After a lot refactoring the code, it works as expected.
Closing this for now.

**Comment by snktshrma** [comment]
Hi @rohithsaro ! Good to know that you sorted this out! You are welcome to do contributions and remove the bug if that seems universal to you.

Thanks
